<html lang="en">

<head>
    <meta name="google-signin-scope" content="profile email">
    <meta name="google-signin-client_id"
          content="866034572539-5lufsq3qfufhgs07lq6d1frc8l1ns73m.apps.googleusercontent.com">
    <script src="https://apis.google.com/js/platform.js" async defer></script>
</head>

<body>
<div class="g-signin2" data-onsuccess="onSignIn" data-theme="dark"></div>
</body>

</html>
